### ISSUE TITLE
Cool design!

### ISSUE THREAD

**Issue by Smokeybear12** [Sxmurai/discord-token-stealer#1]
Never seen a license be able to log people before! How creative!

:trollface:

**Comment by Sxmurai** [comment]
what the MIT license?

**Comment by Sxmurai** [comment]
thats so people can use it their private educational projects

**Comment by Sxmurai** [comment]
oh im retarded lol, just added the code lmao my bad

**Comment by Smokeybear12** [comment]
lmao
